crm/urls.py
from django.urls import path
from .views import *

app_name = 'crm'

urlpatterns = [
    path('teacher/', TeacherAccount.as_view(), name='teacher'),
    path('teacher/get-student/', get_student_by_code, name='get_student'), 
    path('student/', StudentAccount.as_view(), name='student'),
    path('student/profile', StudentProfileView.as_view(), name='student_profile'),
    path('student/tickets', TicketsStudentView.as_view(), name='student_tickets'),
    path("student/materials", MaterialsStudentView.as_view(), name="student_materials"),
    path('adminschool/', AdminSchool.as_view(), name='admin'),
    path('adminschool/lessons/', LessonsView.as_view(), name='lessons'),
    path('adminschool/teachers/', TeachersView.as_view(), name='teachers'),
    path('adminschool/students/', StudentsView.as_view(), name='students'), 
    path('adminschool/students/<int:student_id>/', EditStudentView.as_view(), name='edit_student'),       
    path('adminschool/create-students/', CreateStudentView.as_view(), name='create_student'),
    path('adminschool/create-teacher/', CreateTeacherView.as_view(), name='create_teacher'),
    path('adminschool/materials/', MaterialsAdminView.as_view(), name='materials_admin'),
    path('logout/', logoutUser, name='logout'),
]

fregat/main/urls.py
from django.urls import path
from .views import HomeView, LangView, BlogView, OfertaView, CinemaView, EpisodeView, get_streaming_video

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('lang/', LangView.as_view(), name='lang'),
    path('blog/', BlogView.as_view(), name='blog'),
    path('oferta/', OfertaView.as_view(), name='oferta'),
    path('cinema/', CinemaView.as_view(), name='cinema'),
    path('cinema/<slug:slug>/', EpisodeView.as_view(), name='episode'),
    path('cinema/stream/<slug:slug>/', get_streaming_video, name='stream'),
]

fregat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('school/', include('crm.urls', namespace='crm')),
    path('admin/', admin.site.urls),
    path("ckeditor/", include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('lang/', LangView.as_view(), name='lang'),
    path('blog/', BlogView.as_view(), name='blog'),
    path('oferta/', OfertaView.as_view(), name='oferta'),
    path('cinema/', CinemaView.as_view(), name='cinema'),
    path('cinema/<slug:slug>/', EpisodeView.as_view(), name='episode'),
    path('cinema/stream/<slug:slug>/', get_streaming_video, name='stream'),
    path('signin/', SignIn.as_view(), name='signin'),
]

main/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

class FeedBackForm(forms.Form):
    name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={
            'class': 'block__form__input',
            'placeholder': "Ваше имя"
        })
    )
    
    social = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={
            'class': 'block__form__input',
            'placeholder': "Ваша соц. сеть VK/Telegram/Whatsapp"
        })
    )


class FeedBackFormSecond(forms.Form):
    name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={
            'class': 'block__form__input_second',
            'placeholder': "Ваше имя"
        })
    )
    
    social = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={
            'class': 'block__form__input_second',
            'placeholder': "Ваша соц. сеть VK/Telegram/Whatsapp"
        })
    )
    
    choices_lang = (
        ("-- Все --", 
            (
                ("Английский", "Английский"),
                ("Французский", "Французский"),
                ("Немецкий", "Немецкий"),
                ("Испанский", "Испанский"),
                ("Итальянский", "Итальянский"),
                ("Арабский", "Арабский"),
                ("Китайский", "Китайский"),
                ("Японский", "Японский"),
                ("Корейский", "Корейский"),
                ("Японский", "Японский"),
            )
        ),)

    lang = forms.ChoiceField(choices=choices_lang, label="Выберите язык", required=True, widget=forms.Select(attrs={
        "class": "block__form__input_second"}))


class LevelChoice(forms.Form):
    choices = (
        ("-- Все --", 
            (
                ("A2", "A2"),
                ("B1", "B1"),
                ("B2", "B2"),
            )
        ),)

    level = forms.ChoiceField(choices=choices, label='Выбирете уровень')
    

class SignInForm(AuthenticationForm):
    username = forms.CharField(
        max_length=200,
        widget=forms.TextInput(attrs={
            "class": "block__form__input_second",
            "placeholder": "Логин"})
        )
    password = forms.CharField(
        max_length=200, 
        widget=forms.PasswordInput(attrs={
            "class": "block__form__input_second",
            "placeholder": "Пароль"
        })
    )

fregat/main/views.py
from django.shortcuts import render
from django.views import View
from .forms import FeedBackForm, FeedBackFormSecond, LevelChoice
from django.http import HttpResponseRedirect, StreamingHttpResponse
from django.core.mail import send_mail, BadHeaderError
from main.models import PostBlog, Movie, Episode, Vocabulary, TestCinema, DiscusBoard, SubStory, RightOrder
from django.core.paginator import Paginator
from .services import open_file
from random import shuffle


class HomeView(View):
    def get(self, request, *args, **kwargs):
        form = FeedBackForm()
        sec_form = FeedBackFormSecond()
        return render(
            request,
            'main/home.html', context={
                'form': form,
                'second_form': sec_form
            }
        )
        
    def post(self, request, *args, **kwargs):
        
        
        # === processing forms of communication ===
        if 'first' in self.request.POST:
            form = FeedBackForm(request.POST)
            sec_form = FeedBackFormSecond(request.POST)
            if form.is_valid():
                name = form.cleaned_data['name']
                tel = form.cleaned_data['tel']
                try:
                    send_mail('С вами хотят связаться!', f"{name}. {tel}", 'edik622mujpc@gmail.com', ['edik622mujpc@gmail.com'])
                except BadHeaderError:
                    return 
                return HttpResponseRedirect('/')
            return render(request, 'main/home.html', context={
                'form': form,
                'second_form': sec_form
            })
            
        if 'second' in self.request.POST:
            form = FeedBackForm(request.POST)
            sec_form = FeedBackFormSecond(request.POST)
            if sec_form.is_valid():
                name = sec_form.cleaned_data['name']
                social = sec_form.cleaned_data['social']
                lang = sec_form.cleaned_data['lang']
                try:
                    send_mail('С вами хотят связаться!', f"{name}. Социальная сеть: {social}\nЯзык: {lang}", 'edik622mujpc@gmail.com', ['edik622mujpc@gmail.com'])
                except BadHeaderError:
                    return 
                return HttpResponseRedirect('/')
            return render(request, 'main/home.html', context={
                'form': form,
                'second_form': sec_form
            })
        

class LangView(View):
    def get(self, request, *args, **kwargs):
        form = FeedBackForm()
        sec_form = FeedBackFormSecond()
        return render(
            request,
            'main/lang.html', context={
                'form': form,
                'second_form': sec_form
            }
        )
        
        
    def post(self, request, *args, **kwargs):
        
        
        # === processing forms of communication ===
        if 'first' in self.request.POST:
            form = FeedBackForm(request.POST)
            sec_form = FeedBackFormSecond(request.POST)
            if form.is_valid():
                name = form.cleaned_data['name']
                tel = form.cleaned_data['tel']
                try:
                    send_mail('С вами хотят связаться!', f"{name}. {tel}", 'edik622mujpc@gmail.com', ['edik622mujpc@gmail.com'])
                except BadHeaderError:
                    return 
                return HttpResponseRedirect('/lang')
            return render(request, 'main/lang.html', context={
                'form': form,
                'second_form': sec_form
            })
            
        if 'second' in self.request.POST:
            form = FeedBackForm(request.POST)
            sec_form = FeedBackFormSecond(request.POST)
            if sec_form.is_valid():
                name = sec_form.cleaned_data['name']
                social = sec_form.cleaned_data['social']
                lang = sec_form.cleaned_data['lang']
                try:
                    send_mail('С вами хотят связаться!', f"{name}. Социальная сеть: {social}\nЯзык: {lang}", 'edik622mujpc@gmail.com', ['edik622mujpc@gmail.com'])
                except BadHeaderError:
                    return 
                return HttpResponseRedirect('/lang')
            return render(request, 'main/lang.html', context={
                'form': form,
                'second_form': sec_form
            })
            

class BlogView(View):
    def get(self, request, *args, **kwargs):
        form = FeedBackForm()
        sec_form = FeedBackFormSecond()
        
        # === setting up navigation === 
        posts = PostBlog.objects.all()
        paginator = Paginator(posts, 9)
        
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        # =============================
        
        return render(request, 'main/blog.html', context={
            'page_obj': page_obj,
            'form': form,
            'second_form': sec_form
            })
        
    def post(self, request, *args, **kwargs):
        
        
        # === processing forms of communication ===
        if 'first' in self.request.POST:
            form = FeedBackForm(request.POST)
            sec_form = FeedBackFormSecond(request.POST)
            if form.is_valid():
                name = form.cleaned_data['name']
                tel = form.cleaned_data['tel']
                try:
                    send_mail('С вами хотят связаться!', f"{name}. {tel}", 'edik622mujpc@gmail.com', ['edik622mujpc@gmail.com'])
                except BadHeaderError:
                    return 
                return HttpResponseRedirect('/blog')
            return render(request, 'main/blog.html', context={
                'form': form,
                'second_form': sec_form
            })
            
        if 'second' in self.request.POST:
            form = FeedBackForm(request.POST)
            sec_form = FeedBackFormSecond(request.POST)
            if sec_form.is_valid():
                name = sec_form.cleaned_data['name']
                social = sec_form.cleaned_data['social']
                lang = sec_form.cleaned_data['lang']
                try:
                    send_mail('С вами хотят связаться!', f"{name}. Социальная сеть: {social}\nЯзык: {lang}", 'edik622mujpc@gmail.com', ['edik622mujpc@gmail.com'])
                except BadHeaderError:
                    return 
                return HttpResponseRedirect('/blog')
            return render(request, 'main/blog.html', context={
                'form': form,
                'second_form': sec_form
            })
            

class OfertaView(View):
    def get(self, request, *args, **kwargs):
        form = FeedBackForm()
        sec_form = FeedBackFormSecond()
        return render(request, 'main/oferta.html', context={
                'form': form,
                'second_form': sec_form
            })

    def post(self, request, *args, **kwargs):
        
        
        # === processing forms of communication ===
        if 'first' in self.request.POST:
            form = FeedBackForm(request.POST)
            sec_form = FeedBackFormSecond(request.POST)
            if form.is_valid():
                name = form.cleaned_data['name']
                tel = form.cleaned_data['tel']
                try:
                    send_mail('С вами хотят связаться!', f"{name}. {tel}", 'edik622mujpc@gmail.com', ['edik622mujpc@gmail.com'])
                except BadHeaderError:
                    return 
                return HttpResponseRedirect('/lang')
            return render(request, 'main/lang.html', context={
                'form': form,
                'second_form': sec_form
            })
            
        if 'second' in self.request.POST:
            form = FeedBackForm(request.POST)
            sec_form = FeedBackFormSecond(request.POST)
            if sec_form.is_valid():
                name = sec_form.cleaned_data['name']
                social = sec_form.cleaned_data['social']
                lang = sec_form.cleaned_data['lang']
                try:
                    send_mail('С вами хотят связаться!', f"{name}. Социальная сеть: {social}\nЯзык: {lang}", 'edik622mujpc@gmail.com', ['edik622mujpc@gmail.com'])
                except BadHeaderError:
                    return 
                return HttpResponseRedirect('/oferta')
            return render(request, 'main/lang.html', context={
                'form': form,
                'second_form': sec_form
            })

class CinemaView(View):
    def get(self, request, *args, **kwargs):
        form = FeedBackForm()
        sec_form = FeedBackFormSecond()
        choice_level = LevelChoice()
        
        
        # === we give the selected films using the level ===
        if request.GET.get('lvl'):
            movies_list = Movie.objects.filter(level__level=request.GET.get('lvl'))
            if movies_list:
                return render(request, 
                        'main/cinema.html', context={
                            'form': form,
                            'second_form': sec_form,
                            'movies': movies_list,
                            'choice_level': choice_level
                        })
            else:
                movies_list = Movie.objects.all()
                return render(request, 
                        'main/cinema.html', context={
                            'form': form,
                            'second_form': sec_form,
                            'movies': movies_list,
                            'choice_level': choice_level
                        })
        else:
            movies_list = Movie.objects.all()
            return render(request, 
                    'main/cinema.html', context={
                        'form': form,
                        'second_form': sec_form,
                        'movies': movies_list,
                        'choice_level': choice_level
                    })

main/templates/main/block/footer.html
{% load static %}

<div class="dm-overlay" id="politica">
    <div class="dm-table">
        <div class="dm-cell">
            <div class="dm-modal">
                <a href="#close" class="close"></a>
                <h3 class="form__title">Политика конфиденциальности</h3>
                <p class="text-politica">
					Настоящим я даю согласие Языковой школе «Фрегат» (далее – Оператор) на обработку своих персональных данных, указанных в анкете, в рамках Федерального закона № 152-ФЗ от 27.07.2006 г.<br><br>
                    Конфиденциальность персональных данных соблюдается Оператором в соответствии с требованиями законодательства РФ. Настоящее согласие дается мной на весь срок моей жизни и может быть отозвано мною в любое время путем передачи Оператору моего уведомления.<br><br>
                    Настоящим я выражаю свое согласие предоставлять Оператору право направлять мне информационные сообщения, в т.ч. содержащие информацию маркетингового характера, по указанным мной адресам и номерам мобильных телефонов.<br><br>
                    Я принимаю Политику Конфиденциальности пользуясь сайтом frigateschool.ru
				</p>
            </div>
        </div>
    </div>
</div>

<footer class="footer">
    <div class="container-footer">
        <div class="footer-links">
            <a href="/" class="link-footer">Главная</a>
            <a href="{% url 'main:lang' %}" class="link-footer">Языки</a>
            <a href="/#price" class="link-footer">Стоимость</a>
            <a href="{% url 'main:blog' %}" class="link-footer">Блог</a>
            <a href="#win1" class="link-footer">Связаться</a>
            <a href="{% url 'main:cinema' %}" class="link-footer">Киноклуб</a>
        </div>
        <div class="footer-info">
            <div class="social-media-icons">
                    <a href="https://vk.com/frigateschool" target="_blank">
                        <img src="{% static 'img/vk.png' %}" class="icon-soc" alt="icon">
                    </a>
                    <a href="https://wa.me/+79785502653" target="_blank">
                        <img src="{% static 'img/ws.png' %}" class="icon-soc" alt="icon">
                    </a>
                    <a href="https://t.me/frigateschool" target="_blank">
                        <img src="{% static 'img/tg.png' %}" class="icon-soc" alt="icon" style="margin-top: 3px;">
                    </a>
            </div>
            <p class="footer-text">
                © Языковая школа Фрегат 2021 <a href="https://vk.com/lizulya_mahboula?from=search"><br> Дизайн - Елизавета Муждабаева <br></a> 
                <a href="https://vk.com/hurricane_chroniclenr">Разработка - Муждабаев Эдем</a>
                <a href="#politica">Политика конфиденциальности</a><br>
                <a href="{% url 'main:oferta' %}">Договор оферты</a>
            </p>
        </div>
    </div>
</footer>

main/templates/main/block/header.html
{% load static %}

<div class="dm-overlay" id="win1">
    <div class="dm-table">
        <div class="dm-cell">
            <div class="dm-modal">
                <a href="#close" class="close"></a>
                <h3 class="form__title">Заполните форму, мы свяжемся с вами!</h3>

                <form name="contact-second-form" class="form" action="" method="POST">  
                    {% csrf_token %}
                    {{ second_form.name }}                           
                    {{ second_form.social }}
                    
                    <h4 class="hint-lang">Выберите язык</h4>
                    {{ second_form.lang}}

                    <div class="form__button">
                        <button type="submit" name="second">Отправить</button>
                    </div>

                    <p class="form__title">Напишите нам в мессенджерах:</p>
                    <div class="form__social">
                        <a href="https://vk.com/frigateschool" target="_blank"><img src="{% static 'img/vkform.png' %}" alt="vk"></a>
                        <a href="https://wa.me/+79785502653" target="_blank"><img src="{% static 'img/wsform.png' %}" alt="ws"></a>
                        <a href="https://t.me/frigateschool" target="_blank"><img src="{% static 'img/tgform.png' %}" alt="tg"></a>
                    </div>
                </form>

            </div>
        </div>
    </div>
</div>

<header class="header">
    <div class="header_line"></div>
    <div class="container-nav">
        <div class="nav">
            <div class="mobile-nav">
                <a href="/"><img src="{% static 'img/logo.png' %}" alt="logo" class="logo" id="#id"></a>
                <div onclick="openbox()" class="div-btn-mobile">
                    <img src="{% static 'img/button-mobile.png' %}" alt="btn-img" class="button-mobile">
                </div>
            </div>
            <ul class="nav-list">
                <div class="linehover_block">
                    <li class="mobile-padding-nav"><a href="/#about" class="nav-link">О ФРЕГАТЕ</a></li>
                    <img src="{% static 'img/linehover.png' %}" alt="linehover" class="linehover1">
                </div>
                <div class="linehover_block">
                    <li><a href="{% url 'main:lang' %}" class="nav-link">ЯЗЫКИ</a></li>
                    <img src="{% static 'img/linehover.png' %}" alt="linehover" class="linehover2">
                </div>
                <div class="linehover_block">
                    <li><a href="/#price" class="nav-link">СТОИМОСТЬ</a></li>
                    <img src="{% static 'img/linehover.png' %}" alt="linehover" class="linehover3">
                </div>
                <div class="linehover_block">
                    <li><a href="{% url 'main:blog' %}" class="nav-link">БЛОГ</a></li>
                    <img src="{% static 'img/linehover.png' %}" alt="linehover" class="linehover4">
                </div>
                <div class="linehover_block block__form__hov  mobile-link">
                    <li><a href="/" class="nav-link">СВЯЗАТЬСЯ</a></li>
                    <img src="{% static 'img/linehover.png' %}" alt="linehover" class="linehover5">
                    

                    <div class="block__form">
                        <h1 class="block__form__title">Контакты</h1>
                        <div class="block__form__mail">
                            <img src="{% static 'img/mailform.png' %}" alt="mail">
                            <p class="block__form__mail__text">frigateschool@gmail.com</p>
                        </div>
                        <form name="contact-form" method="POST" class="block__form__form" action="">
                            {% csrf_token %}
                            {{ form.name }}                           
                            {{ form.social }}
                            <div class="block__form__buttonblock">
                                <button type="submit" name="first" class="block__form__button">Записаться</button>
                            </div>                                
                        </form>
                        <p class="block__form__buttom__text">Напишите нам в мессенджерах:</p>
                        <div class="social-media-icons" style="margin-top: 20px;">                           
                            <a href="https://vk.com/frigateschool" class="icon-soc" target="_blank"><svg fill="#875216" width="65px" height="55px" viewBox="0 0 20 20" xmlns="http://www.w3.org/2000/svg" stroke="#875216"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"><path d="M17.802 12.298s1.617 1.597 2.017 2.336a.127.127 0 0 1 .018.035c.163.273.203.487.123.645-.135.261-.592.392-.747.403h-2.858c-.199 0-.613-.052-1.117-.4-.385-.269-.768-.712-1.139-1.145-.554-.643-1.033-1.201-1.518-1.201a.548.548 0 0 0-.18.03c-.367.116-.833.639-.833 2.032 0 .436-.344.684-.585.684H9.674c-.446 0-2.768-.156-4.827-2.327C2.324 10.732.058 5.4.036 5.353c-.141-.345.155-.533.475-.533h2.886c.387 0 .513.234.601.444.102.241.48 1.205 1.1 2.288 1.004 1.762 1.621 2.479 2.114 2.479a.527.527 0 0 0 .264-.07c.644-.354.524-2.654.494-3.128 0-.092-.001-1.027-.331-1.479-.236-.324-.638-.45-.881-.496.065-.094.203-.238.38-.323.441-.22 1.238-.252 2.029-.252h.439c.858.012 1.08.067 1.392.146.628.15.64.557.585 1.943-.016.396-.033.842-.033 1.367 0 .112-.005.237-.005.364-.019.711-.044 1.512.458 1.841a.41.41 0 0 0 .217.062c.174 0 .695 0 2.108-2.425.62-1.071 1.1-2.334 1.133-2.429.028-.053.112-.202.214-.262a.479.479 0 0 1 .236-.056h3.395c.37 0 .621.056.67.196.082.227-.016.92-1.566 3.016-.261.349-.49.651-.691.915-1.405 1.844-1.405 1.937.083 3.337z"></path></g></svg></a>
                            <a href="https://wa.me/+79785502653" class="icon-soc" target="_blank"><svg width="45px" height="55px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" stroke="#875216"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path d="M6.014 8.00613C6.12827 7.1024 7.30277 5.87414 8.23488 6.01043L8.23339 6.00894C9.14051 6.18132 9.85859 7.74261 10.2635 8.44465C10.5504 8.95402 10.3641 9.4701 10.0965 9.68787C9.7355 9.97883 9.17099 10.3803 9.28943 10.7834C9.5 11.5 12 14 13.2296 14.7107C13.695 14.9797 14.0325 14.2702 14.3207 13.9067C14.5301 13.6271 15.0466 13.46 15.5548 13.736C16.3138 14.178 17.0288 14.6917 17.69 15.27C18.0202 15.546 18.0977 15.9539 17.8689 16.385C17.4659 17.1443 16.3003 18.1456 15.4542 17.9421C13.9764 17.5868 8 15.27 6.08033 8.55801C5.97237 8.24048 5.99955 8.12044 6.014 8.00613Z" fill="#875216"></path> <path fill-rule="evenodd" clip-rule="evenodd" d="M12 23C10.7764 23 10.0994 22.8687 9 22.5L6.89443 23.5528C5.56462 24.2177 4 23.2507 4 21.7639V19.5C1.84655 17.492 1 15.1767 1 12C1 5.92487 5.92487 1 12 1C18.0751 1 23 5.92487 23 12C23 18.0751 18.0751 23 12 23ZM6 18.6303L5.36395 18.0372C3.69087 16.4772 3 14.7331 3 12C3 7.02944 7.02944 3 12 3C16.9706 3 21 7.02944 21 12C21 16.9706 16.9706 21 12 21C11.0143 21 10.552 20.911 9.63595 20.6038L8.84847 20.3397L6 21.7639V18.6303Z" fill="#875216"></path> </g></svg></a>
                            <a href="https://t.me/frigateschool" class="icon-soc" target="_blank"><svg width="45px" height="55px" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg"><g id="SVGRepo_bgCarrier" stroke-width="0"></g><g id="SVGRepo_tracerCarrier" stroke-linecap="round" stroke-linejoin="round"></g><g id="SVGRepo_iconCarrier"> <path fill-rule="evenodd" clip-rule="evenodd" d="M23.1117 4.49449C23.4296 2.94472 21.9074 1.65683 20.4317 2.227L2.3425 9.21601C0.694517 9.85273 0.621087 12.1572 2.22518 12.8975L6.1645 14.7157L8.03849 21.2746C8.13583 21.6153 8.40618 21.8791 8.74917 21.968C9.09216 22.0568 9.45658 21.9576 9.70712 21.707L12.5938 18.8203L16.6375 21.8531C17.8113 22.7334 19.5019 22.0922 19.7967 20.6549L23.1117 4.49449ZM3.0633 11.0816L21.1525 4.0926L17.8375 20.2531L13.1 16.6999C12.7019 16.4013 12.1448 16.4409 11.7929 16.7928L10.5565 18.0292L10.928 15.9861L18.2071 8.70703C18.5614 8.35278 18.5988 7.79106 18.2947 7.39293C17.9906 6.99479 17.4389 6.88312 17.0039 7.13168L6.95124 12.876L3.0633 11.0816ZM8.17695 14.4791L8.78333 16.6015L9.01614 15.321C9.05253 15.1209 9.14908 14.9366 9.29291 14.7928L11.5128 12.573L8.17695 14.4791Z" fill="#875216"></path> </g></svg></a>        
                        </div>
                    </div>

                </div>
                <div class="linehover_block club-padding">
                    <li><a href="{% url 'main:cinema' %}" class="nav-link">КИНОКЛУБ</a></li>
                    <img src="{% static 'img/line-cinema.png' %}" alt="linehover" class="linehover6">
                </div>
            </ul>

            <div class="button-nav-block">
                <a href="#win1">
                    <button class="button-nav">ЗАПИСАТЬСЯ НА УРОК</button>
                </a>
            </div>
            <div class="button-nav-block">
                <a href="{% url 'main:signin' %}">
                    <button class="button-nav entrence">ВОЙТИ</button>
                </a>
            </div>
        </div>
    </div>
</header>