crm/urls.py
from django.urls import path
from .views import *

app_name = 'crm'

urlpatterns = [
    path('teacher/', TeacherAccount.as_view(), name='teacher'),
    path('teacher/get-student/', get_student_by_code, name='get_student'), 
    path('student/', StudentAccount.as_view(), name='student'),
    path('student/profile', StudentProfileView.as_view(), name='student_profile'),
    path('student/tickets', TicketsStudentView.as_view(), name='student_tickets'),
    path("student/materials", MaterialsStudentView.as_view(), name="student_materials"),
    path('adminschool/', AdminSchool.as_view(), name='admin'),
    path('adminschool/lessons/', LessonsView.as_view(), name='lessons'),
    path('adminschool/teachers/', TeachersView.as_view(), name='teachers'),
    path('adminschool/students/', StudentsView.as_view(), name='students'), 
    path('adminschool/students/<int:student_id>/', EditStudentView.as_view(), name='edit_student'),       
    path('adminschool/create-students/', CreateStudentView.as_view(), name='create_student'),
    path('adminschool/create-teacher/', CreateTeacherView.as_view(), name='create_teacher'),
    path('adminschool/materials/', MaterialsAdminView.as_view(), name='materials_admin'),
    path('logout/', logoutUser, name='logout'),
]

fregat/main/urls.py
from django.urls import path
from .views import HomeView, LangView, BlogView, OfertaView, CinemaView, EpisodeView, get_streaming_video

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('lang/', LangView.as_view(), name='lang'),
    path('blog/', BlogView.as_view(), name='blog'),
    path('oferta/', OfertaView.as_view(), name='oferta'),
    path('cinema/', CinemaView.as_view(), name='cinema'),
    path('cinema/<slug:slug>/', EpisodeView.as_view(), name='episode'),
    path('cinema/stream/<slug:slug>/', get_streaming_video, name='stream'),
]

fregat/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('main.urls', namespace='main')),
    path('school/', include('crm.urls', namespace='crm')),
    path('admin/', admin.site.urls),
    path("ckeditor/", include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/urls.py
from django.urls import path
from .views import *

app_name = 'main'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('lang/', LangView.as_view(), name='lang'),
    path('blog/', BlogView.as_view(), name='blog'),
    path('oferta/', OfertaView.as_view(), name='oferta'),
    path('cinema/', CinemaView.as_view(), name='cinema'),
    path('cinema/<slug:slug>/', EpisodeView.as_view(), name='episode'),
    path('cinema/stream/<slug:slug>/', get_streaming_video, name='stream'),
    path('signin/', SignIn.as_view(), name='signin'),
]

main/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm

class FeedBackForm(forms.Form):
    name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={
            'class': 'block__form__input',
            'placeholder': "Ваше имя"
        })
    )
    
    social = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={
            'class': 'block__form__input',
            'placeholder': "Ваша соц. сеть VK/Telegram/Whatsapp"
        })
    )


class FeedBackFormSecond(forms.Form):
    name = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={
            'class': 'block__form__input_second',
            'placeholder': "Ваше имя"
        })
    )
    
    social = forms.CharField(
        max_length=100,
        widget=forms.TextInput(attrs={
            'class': 'block__form__input_second',
            'placeholder': "Ваша соц. сеть VK/Telegram/Whatsapp"
        })
    )
    
    choices_lang = (
        ("-- Все --", 
            (
                ("Английский", "Английский"),
                ("Французский", "Французский"),
                ("Немецкий", "Немецкий"),
                ("Испанский", "Испанский"),
                ("Итальянский", "Итальянский"),
                ("Арабский", "Арабский"),
                ("Китайский", "Китайский"),
                ("Японский", "Японский"),
                ("Корейский", "Корейский"),
                ("Японский", "Японский"),
            )
        ),)

    lang = forms.ChoiceField(choices=choices_lang, label="Выберите язык", required=True, widget=forms.Select(attrs={
        "class": "block__form__input_second"}))


class LevelChoice(forms.Form):
    choices = (
        ("-- Все --", 
            (
                ("A2", "A2"),
                ("B1", "B1"),
                ("B2", "B2"),
            )
        ),)

    level = forms.ChoiceField(choices=choices, label='Выбирете уровень')
    

class SignInForm(AuthenticationForm):
    username = forms.CharField(
        max_length=200,
        widget=forms.TextInput(attrs={
            "class": "block__form__input_second",
            "placeholder": "Логин"})
        )
    password = forms.CharField(
        max_length=200, 
        widget=forms.PasswordInput(attrs={
            "class": "block__form__input_second",
            "placeholder": "Пароль"
        })
    )

fregat/main/views.py
from django.shortcuts import render
from django.views import View
from .forms import FeedBackForm, FeedBackFormSecond, LevelChoice
from django.http import HttpResponseRedirect, StreamingHttpResponse
from django.core.mail import send_mail, BadHeaderError
from main.models import PostBlog, Movie, Episode, Vocabulary, TestCinema, DiscusBoard, SubStory, RightOrder
from django.core.paginator import Paginator
from .services import open_file
from random import shuffle


class HomeView(View):
    def get(self, request, *args, **kwargs):
        form = FeedBackForm()
        sec_form = FeedBackFormSecond()
        return render(
            request,
            'main/home.html', context={
                'form': form,
                'second_form': sec_form
            }
        )
        
    def post(self, request, *args, **kwargs):
        
        
        # === processing forms of communication ===
        if 'first' in self.request.POST:
            form = FeedBackForm(request.POST)
            sec_form = FeedBackFormSecond(request.POST)
            if form.is_valid():
                name = form.cleaned_data['name']
                tel = form.cleaned_data['tel']
                try:
                    send_mail('С вами хотят связаться!', f"{name}. {tel}", 'edik622mujpc@gmail.com', ['edik622mujpc@gmail.com'])
                except BadHeaderError:
                    return 
                return HttpResponseRedirect('/')
            return render(request, 'main/home.html', context={
                'form': form,
                'second_form': sec_form
            })
            
        if 'second' in self.request.POST:
            form = FeedBackForm(request.POST)
            sec_form = FeedBackFormSecond(request.POST)
            if sec_form.is_valid():
                name = sec_form.cleaned_data['name']
                social = sec_form.cleaned_data['social']
                lang = sec_form.cleaned_data['lang']
                try:
                    send_mail('С вами хотят связаться!', f"{name}. Социальная сеть: {social}\nЯзык: {lang}", 'edik622mujpc@gmail.com', ['edik622mujpc@gmail.com'])
                except BadHeaderError:
                    return 
                return HttpResponseRedirect('/')
            return render(request, 'main/home.html', context={
                'form': form,
                'second_form': sec_form
            })
        

class LangView(View):
    def get(self, request, *args, **kwargs):
        form = FeedBackForm()
        sec_form = FeedBackFormSecond()
        return render(
            request,
            'main/lang.html', context={
                'form': form,
                'second_form': sec_form
            }
        )
        
        
    def post(self, request, *args, **kwargs):
        
        
        # === processing forms of communication ===
        if 'first' in self.request.POST:
            form = FeedBackForm(request.POST)
            sec_form = FeedBackFormSecond(request.POST)
            if form.is_valid():
                name = form.cleaned_data['name']
                tel = form.cleaned_data['tel']
                try:
                    send_mail('С вами хотят связаться!', f"{name}. {tel}", 'edik622mujpc@gmail.com', ['edik622mujpc@gmail.com'])
                except BadHeaderError:
                    return 
                return HttpResponseRedirect('/lang')
            return render(request, 'main/lang.html', context={
                'form': form,
                'second_form': sec_form
            })
            
        if 'second' in self.request.POST:
            form = FeedBackForm(request.POST)
            sec_form = FeedBackFormSecond(request.POST)
            if sec_form.is_valid():
                name = sec_form.cleaned_data['name']
                social = sec_form.cleaned_data['social']
                lang = sec_form.cleaned_data['lang']
                try:
                    send_mail('С вами хотят связаться!', f"{name}. Социальная сеть: {social}\nЯзык: {lang}", 'edik622mujpc@gmail.com', ['edik622mujpc@gmail.com'])
                except BadHeaderError:
                    return 
                return HttpResponseRedirect('/lang')
            return render(request, 'main/lang.html', context={
                'form': form,
                'second_form': sec_form
            })
            

class BlogView(View):
    def get(self, request, *args, **kwargs):
        form = FeedBackForm()
        sec_form = FeedBackFormSecond()
        
        # === setting up navigation === 
        posts = PostBlog.objects.all()
        paginator = Paginator(posts, 9)
        
        page_number = request.GET.get('page')
        page_obj = paginator.get_page(page_number)
        # =============================
        
        return render(request, 'main/blog.html', context={
            'page_obj': page_obj,
            'form': form,
            'second_form': sec_form
            })
        
    def post(self, request, *args, **kwargs):
        
        
        # === processing forms of communication ===
        if 'first' in self.request.POST:
            form = FeedBackForm(request.POST)
            sec_form = FeedBackFormSecond(request.POST)
            if form.is_valid():
                name = form.cleaned_data['name']
                tel = form.cleaned_data['tel']
                try:
                    send_mail('С вами хотят связаться!', f"{name}. {tel}", 'edik622mujpc@gmail.com', ['edik622mujpc@gmail.com'])
                except BadHeaderError:
                    return 
                return HttpResponseRedirect('/blog')
            return render(request, 'main/blog.html', context={
                'form': form,
                'second_form': sec_form
            })
            
        if 'second' in self.request.POST:
            form = FeedBackForm(request.POST)
            sec_form = FeedBackFormSecond(request.POST)
            if sec_form.is_valid():
                name = sec_form.cleaned_data['name']
                social = sec_form.cleaned_data['social']
                lang = sec_form.cleaned_data['lang']
                try:
                    send_mail('С вами хотят связаться!', f"{name}. Социальная сеть: {social}\nЯзык: {lang}", 'edik622mujpc@gmail.com', ['edik622mujpc@gmail.com'])
                except BadHeaderError:
                    return 
                return HttpResponseRedirect('/blog')
            return render(request, 'main/blog.html', context={
                'form': form,
                'second_form': sec_form
            })
            

class OfertaView(View):
    def get(self, request, *args, **kwargs):
        form = FeedBackForm()
        sec_form = FeedBackFormSecond()
        return render(request, 'main/oferta.html', context={
                'form': form,
                'second_form': sec_form
            })

    def post(self, request, *args, **kwargs):
        
        
        # === processing forms of communication ===
        if 'first' in self.request.POST:
            form = FeedBackForm(request.POST)
            sec_form = FeedBackFormSecond(request.POST)
            if form.is_valid():
                name = form.cleaned_data['name']
                tel = form.cleaned_data['tel']
                try:
                    send_mail('С вами хотят связаться!', f"{name}. {tel}", 'edik622mujpc@gmail.com', ['edik622mujpc@gmail.com'])
                except BadHeaderError:
                    return 
                return HttpResponseRedirect('/lang')
            return render(request, 'main/lang.html', context={
                'form': form,
                'second_form': sec_form
            })
            
        if 'second' in self.request.POST:
            form = FeedBackForm(request.POST)
            sec_form = FeedBackFormSecond(request.POST)
            if sec_form.is_valid():
                name = sec_form.cleaned_data['name']
                social = sec_form.cleaned_data['social']
                lang = sec_form.cleaned_data['lang']
                try:
                    send_mail('С вами хотят связаться!', f"{name}. Социальная сеть: {social}\nЯзык: {lang}", 'edik622mujpc@gmail.com', ['edik622mujpc@gmail.com'])
                except BadHeaderError:
                    return 
                return HttpResponseRedirect('/oferta')
            return render(request, 'main/lang.html', context={
                'form': form,
                'second_form': sec_form
            })

class CinemaView(View):
    def get(self, request, *args, **kwargs):
        form = FeedBackForm()
        sec_form = FeedBackFormSecond()
        choice_level = LevelChoice()
        
        
        # === we give the selected films using the level ===
        if request.GET.get('lvl'):
            movies_list = Movie.objects.filter(level__level=request.GET.get('lvl'))
            if movies_list:
                return render(request, 
                        'main/cinema.html', context={
                            'form': form,
                            'second_form': sec_form,
                            'movies': movies_list,
                            'choice_level': choice_level
                        })
            else:
                movies_list = Movie.objects.all()
                return render(request, 
                        'main/cinema.html', context={
                            'form': form,
                            'second_form': sec_form,
                            'movies': movies_list,
                            'choice_level': choice_level
                        })
        else:
            movies_list = Movie.objects.all()
            return render(request, 
                    'main/cinema.html', context={
                        'form': form,
                        'second_form': sec_form,
                        'movies': movies_list,
                        'choice_level': choice_level
                    })

main/templates/main/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}{% endblock %}</title>
    <link rel="shortcut icon" href="{% static "img/favicon.ico" %}" type="image/png">
    <link rel="stylesheet" href="{% static '/css/main.css' %}">
    <link rel="stylesheet" href="{% static '/css/media.css' %}">
</head>
<body>
    {% include './block/header.html' %}

    {% block content %}

    {% endblock %}

    {% include './block/footer.html' %}
    <script src="{% static 'js/navigation.js' %}"></script>
</body>
</html>

main/templates/main/blog.html
{% extends "./base.html" %}
{% load static %}

{% block title %}Блог - Учи языки на борту Фрегата!{% endblock %}

{% block content %}
    <div class="blog-background-info-header">
        <div>
            <div class="container">
                <div class="blog-block-text-header">
                    <img src="{% static 'img/circle.png' %}" alt="circle" class="circle circle-blog">
                    <p class="blog__info__header__title">Блог - сундук с сокровищами</p>
                    <div class="blog__info__two__block">
                        <p class="two__block__title">
                            потому что здесь мы храним все секретные знания.
                            Читай и прокачивай свои навыки.
                        </p>
                        <img src="{% static 'img/arrow.png' %}" alt="arrow" class="arrow">
                    </div>
                    <p class="text-price">Здесь вы найдёте:</p>
                    <ul style="margin-top: 30px;">
                        <li class="price-text-li">мотивационные статьи</li>
                        <li class="price-text-li">уникальные методы запоминания слов</li>
                        <li class="price-text-li">советы по изучению языков</li>
                        <li class="price-text-li">культурные особенности</li>
                        <li class="price-text-li">истории из жизни преподавателей</li>
                        <li class="price-text-li">кейсы учеников</li>
                    </ul>
                    <div class="img__bg__top">
                        <img src="{% static 'img/blog-bg-1.png' %}" alt="animation">
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="line-section" style="margin-top: 30px;background-color: #f8abbf"></div>

    <main class="main-blog">
        <div>
            <div class="posts_div">
                {% for post in page_obj %}
                    <a href="#{{ post.url }}">
                        <div class="blog-card">
                            <img src="../media/{{ post.img }}" alt="" class="blog-img">
                            <div class="blog-title">
                                {{ post.title }}
                            </div>
                        </div>
                    
                    <div class="dm-overlay" id="{{ post.url }}">
                        <div class="dm-table">
                            <div class="dm-cell">
                                <div class="dm-modal2">
                                    <a href="#close" class="close"></a>
                                    <h1>{{ post.title }}</h1>
                                    {{ post.text|safe }}
                                </div>
                            </div>
                        </div>
                    </div>

                {% endfor %}
            </div>  

            
            <!-- pagination -->
        
            <div class="pagination">
                <ul class="pagination modal-4" id="pagination">
                    {% if page_obj.has_previous %}
                        <li><a href="?page={{ page_obj.previous_page_number }}" class="prev"><</a></li>
                    {% else %}
                        <li><a href="#" class="prev disabled_a" tabindex="-1"><</a></li>
                    {% endif %}
            
                    {% for page in page_obj.paginator.page_range %}
                        <li class="page-item" data-page="{{ page }}">
                            <a href="?page={{ page }}" class="{% if page == page_obj.number %}active{% endif %}">{{ page }}</a>
                        </li>
                    {% endfor %}
            
                    {% if page_obj.has_next %}
                        <li><a href="?page={{ page_obj.next_page_number }}" class="next">></a></li>
                    {% else %}
                        <li><a href="#" class="next disabled_a">></a></li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </main>

    <script>
        document.addEventListener('DOMContentLoaded', function() {
            const pagination = document.getElementById('pagination');
            const pageItems = Array.from(pagination.getElementsByClassName('page-item'));
            const totalPages = pageItems.length; // Общее количество страниц
            const currentPage = parseInt(pagination.querySelector('.active') ? pagination.querySelector('.active').textContent : 1);
    
            function updatePagination() {
                // Скрываем все элементы
                pageItems.forEach(item => {
                    item.style.display = 'none';
                });
    
                let startPage, endPage;
    
                // Логика для отображения страниц
                if (window.innerWidth < 768) {
                    // Мобильная версия: показываем 3 страницы
                    if (totalPages <= 3) {
                        startPage = 1;
                        endPage = totalPages;
                    } else {
                        if (currentPage === 1) {
                            startPage = 1;
                            endPage = 3;
                        } else if (currentPage === totalPages) {
                            startPage = totalPages - 2;
                            endPage = totalPages;
                        } else {
                            startPage = currentPage - 1;
                            endPage = currentPage + 1;
    
                            // Корректируем границы
                            if (startPage < 1) {
                                startPage = 1;
                                endPage = 3;
                            }
                            if (endPage > totalPages) {
                                endPage = totalPages;
                                startPage = totalPages - 2;
                            }
                        }
                    }
                } else {
                    // Десктопная версия: показываем 5 страниц
                    if (totalPages <= 5) {
                        startPage = 1;
                        endPage = totalPages;
                    } else {
                        if (currentPage <= 3) {
                            startPage = 1;
                            endPage = 5;
                        } else if (currentPage >= totalPages - 2) {
                            startPage = totalPages - 4;
                            endPage = totalPages;
                        } else {
                            startPage = currentPage - 2;
                            endPage = currentPage + 2;
                        }
                    }
                }
    
                // Отображаем нужные страницы
                for (let i = startPage; i <= endPage; i++) {
                    pageItems[i - 1].style.display = 'list-item'; // Индексируем с 0
                }
            }
    
            updatePagination();
    
            // Обновляем пагинацию при изменении размера окна
            window.addEventListener('resize', updatePagination);
        });
    </script>
{% endblock %}

main/templates/main/cinema.html
{% extends "./base.html" %}
{% load static %}

{% block title %}Киноклуб — Учи языки на борту Фрегата!{% endblock %}

{% block content %}
    <main style="margin: 0 auto;">
        <div class="cinema-page">
            <form name="level-form" method="POST" class="level-form">
                {% csrf_token %}
                Выбирете уровень:{{ choice_level.level }}
                <input type = "submit" value = "Подтвердить" class="level-btn">
            </form>
            
            <div class="cinema-films">
                {% for movie in movies %}
                    <div class="cinema-film">
                        <a href="{% url 'main:episode' movie.episodes.all.0.url %}" class="cinema-film__linkImg"><img src="../media/{{ movie.img }}" alt="logo_film"></a>
                        <div style="margin: 18px 0 8px;">
                            <a href="{% url 'main:episode' movie.episodes.all.0.url %}" class="cinema-film__title">{{ movie.title }}</a>
                        </div>
                         <div class="film-episodes"> 
                            {% for episode in movie.episodes.all %}
                                <div style="margin: 0 13px 8px 0;"><a href="{% url 'main:episode' episode.url %}" class="episode-link">episode {{episode.number_epis}}</a></div>
                            {% endfor %}
                        </div> 
                    </div>
                {% endfor %} 
            </div>
        </div>
    </main> 
{% endblock %}

main/templates/main/signin.html
{% extends "./base.html" %}
{% load static %}

{%block title%}Вход в аккаунт{% endblock %}


{% block content %}
    <div class="container-signin">
        <div class="card-signin">
            <p class="signin-header">ВХОД</p>
            <form name="sign_in_form" class="signin-form" method="POST">
                {% csrf_token %}
                {{ sign_form.username }}
                {{ sign_form.password }}

                {% if sign_form.non_field_errors %}
                    <div class="alert alert-danger">
                        {{ sign_form.non_field_errors }}
                    </div>
                {% endif %}
                
                <div class="form__button">
                    <button type="submit" name="signin">Отправить</button>
                </div>
            </form>
        </div>
    </div>
{% endblock %}